### PR TITLE
Add timestamp to scope_info and target_info GMP metrics

### PR DESCRIPTION
**Pull request by damemi**
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/584

### CODE REVIEW

**Comment by dashpole** [comment]
I think it is reasonable to fix it this way for now, and we should try to make sure we get this fixed upstream ASAP, since it produces errors when using the GMP exporter.  We should make an issue to track a solution to the problems this creates below:

It is possible that the collector will be exporting a batch of metrics that are old (e.g. if metrics have been persisted to disk for an hour from on-prem before sending if there was a network outage).  In that case, the timestamp of the target_info metric would be now() but the timestamp on the metrics would be an hour ago, which is odd.  It could also cause the timestamps of multiple batches to be very close together if, for example, i'm backfilling historical data sequentially.  In that case, the timestamps of my regular metrics would be far apart (because they were collected at regular intervals), but if they are uploaded quickly, I would get a bunch of target_info and scope_info metrics that are really close together in time, and could cause write errors.

The [solution adopted by the PRW exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7aac7c8f0fe31ad0eb07484018c22ec954822463/pkg/translator/prometheusremotewrite/metrics_to_prw.go#L47) is to use the most recent timestamp in the metrics contained within the resource/scope.

**Comment by damemi** [comment]
@dashpole no I agree doing it right makes sense now. should we revert the broken release or just publish the new one asap?

**Review by dashpole — APPROVED** [review]
nice.  Didn't think the fix would be that quick

**Comment by dashpole** [comment]
feel free to merge with coverage checks failing.

**Pull request merged**
