### PR TITLE
Upgrade otel collector and go library

### PR DESCRIPTION
**Pull request by bogdandrutu**
Also removed usage of deprecated `ioutil` package

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by dashpole — APPROVED** [review]

**Comment by dashpole** [comment]
Would you mind running `make fixtures` and committing the result?  It should fix the unit test failure.

**Comment by dashpole** [comment]
:/. Seems like a recurrence of https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/421.

Can you run `make fixtures` again? Sorry

**Comment by bogdandrutu** [comment]
It is not that, since `make fixtures` run multiple times does not produce any diff.

**Comment by damemi** [comment]
I think it could still be #421, the diff looks like we are sorting on the MetricDescriptorRequest names, but not the names of the MetricDescriptors within those requests. Working on a fix to test it. Unfortunately this is tough to reproduce locally because it's essentially random which sorted order you're going to get, so it could keep passing locally and showing no diff but fail in CI

**Comment by damemi** [comment]
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/469 is passing but @bogdandrutu it looks like your changes in [Sort all the metrics](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/468/commits/89bfa35a33fccf607bc3feee290a8e5fdcfaef7a) will also work. If that goes green we can just close my PR (but you might still have to run `make fixtures` again to pick up the new sorting)

**Comment by bogdandrutu** [comment]
@damemi just merge that and I will rebase.

**Comment by damemi** [comment]
@bogdandrutu sorry for the delay, merged now

**Pull request merged**
