### PR TITLE
exporter/trace: upgrade and cleanup all modules

### PR DESCRIPTION
**Pull request by zchee**
Upgrade and cleanup all modules.
Passes all tests.

### CODE REVIEW

**Comment by zchee** [comment]
Failed CI because of follows lint error:
```console
.
.
trace.go:25:2: SA1019: Package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (staticcheck)
 
	"github.com/golang/protobuf/proto"
 ```

Can I replace `github.com/golang/protobuf/proto` package to `google.golang.org/protobuf/proto` in another PR? or just add `lint:ignore` pragma?

**Comment by james-bebbington** [comment]
> Can I replace `github.com/golang/protobuf/proto` package to `google.golang.org/protobuf/proto` in another PR? or just add `lint:ignore` pragma?

I think it's okay to add a lint ignore for now. Would be good to make an attempt to update to `google.golang.org/protobuf/proto` though I'm not sure how straightforward that will be.

Note the Go SDK just switched to generating code from protos there, so there will be some package changes coming anyway: https://github.com/open-telemetry/opentelemetry-go/pull/942/files

**Comment by zchee** [comment]
@james-bebbington 
> I think it's okay to add a lint ignore for now. Would be good to make an attempt to update to google.golang.org/protobuf/proto though I'm not sure how straightforward that will be.

I see.
I'd commit which added `//nolint:staticcheck` pragma. PTAL.

**Comment by james-bebbington** [comment]
Sorry I just merged another PR so you will need to rebase this

**Comment by zchee** [comment]
@james-bebbington rebased and remove `//nolint:staticcheck` commit since already changed `google.golang.org/protobuf/proto` package.
PTAL again.

**Pull request merged**
