### PR TITLE
Remove deprecated Flags API

### PR DESCRIPTION
**Pull request by TylerHelmuth**
Upgrades the collector libraries to 0.57.2 and removes the deprecated Flags API in favor of FlagsStruct.  Let me know if the package upgrade needs to be done in a separate PR.

### CODE REVIEW

**Comment by dashpole** [comment]
/gcbrun
Thanks!

**Review by dashpole — APPROVED** [review]

**Comment by dashpole** [comment]
looks like it needs a `make gotidy`?

**Comment by TylerHelmuth** [comment]
> looks like it needs a make gotidy?

@dashpole done

**Pull request merged**
