### PR TITLE
[chore] Update otel collector dependency to 0.62.0

### PR DESCRIPTION
**Pull request by dmitryax**
Adopt code to the following otel collector core API deprecations:
- https://github.com/open-telemetry/opentelemetry-collector/pull/6261
- https://github.com/open-telemetry/opentelemetry-collector/pull/6259
- https://github.com/open-telemetry/opentelemetry-collector/pull/6253
- https://github.com/open-telemetry/opentelemetry-collector/pull/6210

### CODE REVIEW

**Comment by dmitryax** [comment]
Hm... I've signed the CLA, not sure why the check if failing

**Comment by dashpole** [comment]
You did the CLA with your gmail, right?  That is on the commit

**Comment by dmitryax** [comment]
> You did the CLA with your gmail, right? That is on the commit

Yes

**Comment by dashpole** [comment]
/gcbrun

There was a "rescan" button in the CLA check text.  That seems to have fixed it

**Comment by dmitryax** [comment]
> There was a "rescan" button in the CLA check text. That seems to have fixed it

Thanks!

**Review by dashpole — APPROVED** [review]

**Pull request merged**
