### PR TITLE
Add support for non-string metric labels

### PR DESCRIPTION
**Pull request by ronilichtman**
This is a follow-up to #217 which added support for monitored resource labels. In this PR we add support for metric labels.

Context: #218

### CODE REVIEW

**Comment by dashpole** [comment]
Would you mind adding a unit test?

**Comment by ronilichtman** [comment]
Hey David, I initially hoped to leverage the existing `TestRecordToMpb` test from https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/metric/metric_test.go#L154, but couldn't get it to work.

Specifically, I changed the the strings that it expects (i.e. the "b_b" string to "b_b1234") and the test always passes essentially ignoring the `want` variable. I'm unsure how to integrate into that test, do you mind if I write a `TestRecordToMpb_NonStringAttributes` case which looks a bit different?

**Comment by dashpole** [comment]
Feel free to write a new test that is specifically for this change.

**Comment by dashpole** [comment]
i'll add the test myself in a follow-up.

**Review by dashpole — APPROVED** [review]

**Pull request merged**
