### PR TITLE
[chore] Update OTel dependencies

### PR DESCRIPTION
**Pull request by dmitryax**
And adopt code to the collector API changes

### CODE REVIEW

**Review by damemi — APPROVED** [review]

**Comment by damemi** [comment]
@dmitryax can you run `make fixtures`?

**Review by damemi — CHANGES_REQUESTED** [review]
(needs test fixture update)

**Comment by dmitryax** [comment]
> @dmitryax can you run make fixtures?

Done 👍

**Comment by dmitryax** [comment]
@damemi looks like the e2e failures are the same as in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/537. Are they flaky? Can be ignored?

**Comment by damemi** [comment]
@dmitryax good question, I was trying to look into that. @dashpole do you have any idea about the e2e failures? Looks like it's having trouble on the google cloud end:
```
=== RUN   TestBasicTrace
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:85: 
        	Error Trace:	trace_test.go:85
        	            				trace_test.go:106
        	Error:      	Received unexpected error:
        	            	retryable: googleapi: Error 404: Requested entity was not found., notFound
        	Test:       	TestBasicTrace
--- FAIL: TestBasicTrace (13.00s)
=== RUN   TestResourceDetectionTrace
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
=== RUN   TestResourceDetectionTrace/Span_has_label_g.co/agent
=== RUN   TestResourceDetectionTrace/Span_has_label_test_id
=== RUN   TestResourceDetectionTrace/Span_has_label_g.co/r/gce_instance/zone
=== RUN   TestResourceDetectionTrace/Span_has_label_g.co/r/gce_instance/instance_id
--- PASS: TestResourceDetectionTrace (3.29s)
    --- PASS: TestResourceDetectionTrace/Span_has_label_g.co/agent (0.00s)
    --- PASS: TestResourceDetectionTrace/Span_has_label_test_id (0.00s)
    --- PASS: TestResourceDetectionTrace/Span_has_label_g.co/r/gce_instance/zone (0.00s)
    --- PASS: TestResourceDetectionTrace/Span_has_label_g.co/r/gce_instance/instance_id (0.00s)
=== RUN   TestComplexTrace
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:80: Retrying GetTrace: googleapi: Error 404: Requested entity was not found., notFound
    trace_test.go:85: 
        	Error Trace:	trace_test.go:85
        	            				trace_test.go:278
        	Error:      	Received unexpected error:
        	            	retryable: googleapi: Error 404: Requested entity was not found., notFound
        	Test:       	TestComplexTrace
--- FAIL: TestComplexTrace (13.90s)
```

**Comment by dashpole** [comment]
Are there any logs from the test server?  Did it successfully write the span it is complaining about not finding?

**Comment by bogdandrutu** [comment]
@damemi @dashpole can you please help us unblock the last standing PR for pdata stability :)

**Review by damemi — APPROVED** [review]

**Pull request merged**
