### PR TITLE
Refactor exporter creation functions.

### LINKED ISSUE #193: Refactor Creation Functions
We should follow the pattern set by https://github.com/open-telemetry/opentelemetry-go/pull/1985 so we remain consistent with other exporters.

### PR DESCRIPTION
**Pull request by dashpole**
This renames `NewExporter` to `New`, and removes `InstallNewPipeline` and `NewExportPipeline`.

Users can replace:
```golang
tp, shutdown, err := exporter.InstallNewPipeline(exporterOpts, sdkOpts...)
// handle error
defer shutdown()
```
With:
```golang
exporter, err := exporter.New(exporterOpts)
// handle error
tp := sdktrace.NewTracerProvider(sdktrace.WithBatcher(exporter), sdkOpts...)
defer tp.Shutdown(context.Background())
otel.SetTracerProvider(tp)
```

And can replace:

```golang
tp, shutdown, err := exporter.NewExportPipeline(exporterOpts, sdkOpts...)
// handle error
defer shutdown()
```
With:
```golang
exporter, err := exporter.New(exporterOpts)
// handle error
tp := sdktrace.NewTracerProvider(sdktrace.WithBatcher(exporter), sdkOpts...)
defer tp.Shutdown(context.Background())
```

Fixes #193

This also removes the need for BatchSpanProcessorOptions (which you couldn't actually set anyways...).

### CODE REVIEW

**Review by aabmass — COMMENTED** [review]
Code LGTM. Is it clear to users how to migrate to this, and were there any GCP specific defaults we are losing?

**Comment by dashpole** [comment]
Is the above description sufficient, or should we document this elsewhere?

**Review by aabmass — APPROVED** [review]
I guess this is good enough, the PR should be in the release notes

**Comment by dashpole** [comment]
@punya I would like your review on this

**Review by punya — APPROVED** [review]
Thanks, this is a big improvement to the API. I'll take care of documenting it in the release notes, as well as upgrading the collector exporter.

**Pull request merged**
